export const datingpool = [
    {
        id: 0,
        name: "Alex",
        gender: "Male",
        pronouns: "He/Him",
        birthday: "Summer 13",
        location: [{address: "1 River Road", link: "https://stardewvalleywiki.com/1_River_Road"}],
        bio: `Alex loves sports and hanging out at the beach. He is quite arrogant and brags to everyone that he is going to be a professional athlete. Is his cockiness just a facade to mask his crushing self-doubt? Is he using his sports dream to fill the void left by the disappearance of his parents? Or is he just a brazen youth trying to "look cool?"`,
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Complete Breakfast", link: "https://stardewvalleywiki.com/Complete_Breakfast"}, {item: "Salmon Dinner", link: "https://stardewvalleywiki.com/Salmon_Dinner"}],
        likes: [{item: "All Universal Likes", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "All Eggs (see: exceptions)", link: "https://stardewvalleywiki.com/Egg"}],
        dislikes: "",
        events: []
    },
    {
        id: 1,
        name: "Elliott",
        gender: "Male",
        pronouns: "He/Him",
        birthday: "Fall 5",
        location: [{address: "Cabin on the Beach", link: "https://stardewvalleywiki.com/Elliott%27s_Cabin"}],
        bio: `Elliott lives alone in a cabin on the beach. He is a writer who dreams of one day writing a magnificent novel. He is a sentimental "romantic" with a tendency to go off onto flowery, poetic tangents. When he can afford it, he enjoys a strong beverage at the Stardrop Saloon. Could a humble farmer such as yourself be the inspiration Elliott is looking for? There’s only one way to find out…`,
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Crab Cakes", link: "https://stardewvalleywiki.com/Crab_Cakes"}, {item: "Duck Feather", link: "https://stardewvalleywiki.com/Duck_Feather"}, {item: "Lobster", link: "https://stardewvalleywiki.com/Lobster"}, {item: "Pomegranate", link: "https://stardewvalleywiki.com/Pomegranate"}, {item: "Squid Ink", link: "https://stardewvalleywiki.com/Squid_Ink"}, {item: "Tom Kha Soup", link: "https://stardewvalleywiki.com/Tom_Kha_Soup"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "All Fruit (see: exceptions)", link: "https://stardewvalleywiki.com/Fruits"}, {item: "Octopus", link: "https://stardewvalleywiki.com/Octopus"}, {item: "Squid", link: "https://stardewvalleywiki.com/Squid"}],
        dislikes: "",
        events: []
    },
    {
        id: 2,
        name: "Harvey",
        gender: "Male",
        pronouns: "He/Him",
        birthday: "Winter 14",
        location: [{address: "Medical Clinic", link: "https://stardewvalleywiki.com/Harvey%27s_Clinic"}],
        bio: "Harvey is the town doctor. He’s a little old for a bachelor, but he has a kind heart and a respected position in the community. He lives in a small apartment above the medical clinic, but spends most of his time working. You can sense a sadness about him, as if there's something he's not telling you…",
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Coffee", link: "https://stardewvalleywiki.com/Coffee"}, {item: "Pickles", link: "https://stardewvalleywiki.com/Jellies_and_Pickles"}, {item: "Super Meal", link: "https://stardewvalleywiki.com/Super_Meal"}, {item: "Truffle Oil", link: "https://stardewvalleywiki.com/Truffle_Oil"}, {item: "Wine", link: "https://stardewvalleywiki.com/Wine"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "All Fruit (see: exceptions)", link: "https://stardewvalleywiki.com/Fruits"}, {item: "Chanterelle", link: "https://stardewvalleywiki.com/Chanterelle"}, {item: "Common Mushroom", link: "https://stardewvalleywiki.com/Common_Mushroom"}, {item: "Daffodil", link: "https://stardewvalleywiki.com/Daffodil"}, {item: "Dandelion", link: "https://stardewvalleywiki.com/Dandelion"}, {item: "Duck Egg", link: "https://stardewvalleywiki.com/Duck_Egg"}, {item: "Duck Feather", link: "https://stardewvalleywiki.com/Duck_Feather"}, {item: "Ginger", link: "https://stardewvalleywiki.com/Ginger"}, {item: "Goat Milk", link: "https://stardewvalleywiki.com/Goat_Milk"}, {item: "Hazelnut", link: "https://stardewvalleywiki.com/Hazelnut"}, {item: "Holly", link: "https://stardewvalleywiki.com/Holly"}, {item: "Large Goat Milk", link: "https://stardewvalleywiki.com/Large_Goat_Milk"}, {item: "Leek", link: "https://stardewvalleywiki.com/Leek"}, {item: "Magma Cap", link: "https://stardewvalleywiki.com/Magma_Cap"}, {item: "Morel", link: "https://stardewvalleywiki.com/Morel"}, {item: "Purple Mushroom", link: "https://stardewvalleywiki.com/Purple_Mushroom"}, {item: "Quartz", link: "https://stardewvalleywiki.com/Quartz"}, {item: "Snow Yam", link: "https://stardewvalleywiki.com/Snow_Yam"}, {item: "Spring Onion", link: "https://stardewvalleywiki.com/Spring_Onion"}, {item: "Wild Horseradish", link: "https://stardewvalleywiki.com/Wild_Horseradish"}, {item: "Winter Root", link: "https://stardewvalleywiki.com/Winter_Root"}],
        dislikes: "",
        events: []
    },
    {
        id: 3,
        name: "Sam",
        gender: "Male",
        pronouns: "He/Him",
        birthday: "Summer 17",
        location: [{address: "1 Willow Lane", link: "https://stardewvalleywiki.com/1_Willow_Lane"}],
        bio: "Sam is an outgoing, friendly guy who is brimming with youthful energy. He plays guitar and drums, and wants to start a band with Sebastian as soon as he has enough songs together. However, he does have a habit of starting ambitious projects and not finishing them. Sam is a little stressed about the impending return of his father, who has been away for years due to his line of work.",
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Cactus Fruit", link: "https://stardewvalleywiki.com/Cactus_Fruit"}, {item: "Maple Bar", link: "https://stardewvalleywiki.com/Maple_Bar"}, {item: "Pizza", link: "https://stardewvalleywiki.com/Pizza"}, {item: "Tigerseye", link: "https://stardewvalleywiki.com/Tigerseye"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "All Eggs (see: exceptions)", link: "https://stardewvalleywiki.com/Egg"}, {item: "Joja Cola", link: "https://stardewvalleywiki.com/Joja_Cola"}],
        dislikes: "",
        events: []
    },
    {
        id: 4,
        name: "Sebastian",
        gender: "Male",
        pronouns: "He/Him",
        birthday: "Winter 10",
        location: [{address: "24 Mountain Road", link: "https://stardewvalleywiki.com/Carpenter%27s_Shop"}],
        bio: "Sebastian is a rebellious loner who lives in his parents' basement. He is Maru's older half-brother, and feels like his sister gets all the attention and adoration, while he is left to rot in the dark. He tends to get deeply absorbed in his work, computer games, comic books, sci-fi novels, and will sometimes spend great lengths of time pursuing these hobbies alone in his room. He can be a bit unfriendly to people he doesn't know. Could a charming new farmer cultivate the wasteland of his heart? Who knows?",
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Frozen Tear", link: "https://stardewvalleywiki.com/Frozen_Tear"}, {item: "Obsidian", link: "https://stardewvalleywiki.com/Obsidian"}, {item: "Pumpkin Soup", link: "https://stardewvalleywiki.com/Pumpkin_Soup"}, {item: "Sashimi", link: "https://stardewvalleywiki.com/Sashimi"}, {item: "Void Egg", link: "https://stardewvalleywiki.com/Void_Egg"}],
        likes: [{item: `All Universal Likes (see: exceptions)`, link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "Flounder", link: "https://stardewvalleywiki.com/Flounder"}, {item: "Quartz", link: "https://stardewvalleywiki.com/Quartz"}],
        dislikes: "",
        events: []
    },
    {
        id: 5,
        name: "Shane",
        gender: "Male",
        pronouns: "He/Him",
        birthday: "Spring 20",
        location: [{address: "Marnie's Ranch", link: "https://stardewvalleywiki.com/Marnie%27s_Ranch"}],
        bio: "I'm renting my room from Marnie at a really good price. It's small but I can't complain. If I could reset my life maybe I'd start a chicken farm. Only free-range eggs of course.",
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Beer", link: "https://stardewvalleywiki.com/Beer"}, {item: "Hot Pepper", link: "https://stardewvalleywiki.com/Hot_Pepper"}, {item: "Pepper Poppers", link: "https://stardewvalleywiki.com/Pepper_Poppers"}, {item: "Pizza", link: "https://stardewvalleywiki.com/Pizza"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "All Eggs (see: exceptions)", link: "https://stardewvalleywiki.com/Egg"}, {item: "All Fruit (see: exceptions)", link: "https://stardewvalleywiki.com/Fruits"}],
        dislikes: "",
        events: []
    },
    {
        id: 6,
        name: "Abigail",
        gender: "Female",
        pronouns: "She/Her",
        birthday: "Fall 13",
        location: [{address: "Pierre's General Store", link: "https://stardewvalleywiki.com/Pierre%27s_General_Store"}],
        bio: `Abigail lives at the general store with her parents. She sometimes fights with her mom, who worries about Abigail's "alternative lifestyle". Her mom has the following to say: "I wish Abby would dress more appropriately and stop dyeing her hair blue. She has such a wonderful natural hair color, just like her grandmother did. Oh, and I wish she'd find some wholesome interests instead of this occult nonsense she's into." You might find Abigail alone in the graveyard, or maybe out in a rainstorm looking for frogs.`,
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Amethyst", link: "https://stardewvalleywiki.com/Amethyst"}, {item: "Banana Pudding", link: "https://stardewvalleywiki.com/Banana_Pudding"}, {item: "Blackberry Cobbler", link: "https://stardewvalleywiki.com/Blackberry_Cobbler"}, {item: "Chocolate Cake", link: "https://stardewvalleywiki.com/Chocolate_Cake"}, {item: "Pufferfish", link: "https://stardewvalleywiki.com/Pufferfish"}, {item: "Pumpkin", link: "https://stardewvalleywiki.com/Pumpkin"}, {item: "Spicy Eel", link: "https://stardewvalleywiki.com/Spicy_Eel"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "Quartz", link: "https://stardewvalleywiki.com/Quartz"}],
        dislikes: "",
        events: []
    },
    {
        id: 7,
        name: "Emily",
        gender: "Female",
        pronouns: "She/Her",
        birthday: "Spring 27",
        location: [{address: "2 Willow Lane", link: "https://stardewvalleywiki.com/2_Willow_Lane"}],
        bio: "I'm just working at Gus' to make ends meet... but my real passion is tailoring. I made these clothes from scratch.",
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Amethyst", link: "https://stardewvalleywiki.com/Amethyst"}, {item: "Aquamarine", link: "https://stardewvalleywiki.com/Aquamarine"}, {item: "Cloth", link: "https://stardewvalleywiki.com/Cloth"}, {item: "Emerald", link: "https://stardewvalleywiki.com/Emerald"}, {item: "Jade", link: "https://stardewvalleywiki.com/Jade"}, {item: "Ruby", link: "https://stardewvalleywiki.com/Ruby"}, {item: "Survival Burger", link: "https://stardewvalleywiki.com/Survival_Burger"}, {item: "Topaz", link: "https://stardewvalleywiki.com/Topaz"}, {item: "Wool", link: "https://stardewvalleywiki.com/Wool"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "Daffodil", link: "https://stardewvalleywiki.com/Daffodil"}, {item: "Quartz", link: "https://stardewvalleywiki.com/Quartz"}],
        dislikes: "",
        events: []
    },
    {
        id: 8,
        name: "Haley",
        gender: "Female",
        pronouns: "She/Her",
        birthday: "Spring 14",
        location: [{address: "2 Willow Lane", link: "https://stardewvalleywiki.com/2_Willow_Lane"}],
        bio: "Being wealthy and popular throughout high school has made Haley a little conceited and self-centered. She has a tendency to judge people for superficial reasons. But is it too late for her to discover a deeper meaning to life? Is there a fun, open-minded young woman hidden within that candy-coated shell?",
        loves: [{item: "All Universal Loves (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Coconut", link: "https://stardewvalleywiki.com/Coconut"}, {item: "Fruit Salad", link: "https://stardewvalleywiki.com/Fruit_Salad"}, {item: "Pink Cake", link: "https://stardewvalleywiki.com/Pink_Cake"}, {item: "Sunflower", link: "https://stardewvalleywiki.com/Sunflower"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "Daffodil", link: "https://stardewvalleywiki.com/Daffodil"}],
        dislikes: "",
        events: []
    },
    {
        id: 9,
        name: "Leah",
        gender: "Female",
        pronouns: "She/Her",
        birthday: "Winter 23",
        location: [{address: "Cottage south of Marnie's Ranch", link: "https://stardewvalleywiki.com/Leah%27s_Cottage"}],
        bio: "Leah lives alone in a small cabin just outside of town. She loves to spend time outside, foraging for a wild meal or simply enjoying the gifts of the season. She's a talented artist with a large portfolio of work… yet she's too nervous to display it to the public. Maybe you can give her a little confidence boost?",
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Goat Cheese", link: "https://stardewvalleywiki.com/Goat_Cheese"}, {item: "Poppyseed Muffin", link: "https://stardewvalleywiki.com/Poppyseed_Muffin"}, {item: "Salad", link: "https://stardewvalleywiki.com/Salad"}, {item: "Stir Fry", link: "https://stardewvalleywiki.com/Stir_Fry"}, {item: "Truffle", link: "https://stardewvalleywiki.com/Truffle"}, {item: "Vegetable Medley", link: "https://stardewvalleywiki.com/Vegetable_Medley"}, {item: "Wine", link: "https://stardewvalleywiki.com/Wine"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "All Eggs (see: exceptions)", link: "https://stardewvalleywiki.com/Egg"}, {item: "All Fruit", link: "https://stardewvalleywiki.com/Fruits"}, {item: "All Milk", link: "https://stardewvalleywiki.com/Milk"}, {item: "Blackberry", link: "https://stardewvalleywiki.com/Blackberry"}, {item: "Chanterelle", link: "https://stardewvalleywiki.com/Chanterelle"}, {item: "Common Mushroom", link: "https://stardewvalleywiki.com/Common_Mushroom"}, {item: "Daffodil", link: "https://stardewvalleywiki.com/Daffodil"}, {item: "Dandelion", link: "https://stardewvalleywiki.com/Dandelion"}, {item: "Driftwood", link: "https://stardewvalleywiki.com/Driftwood"}, {item: "Ginger", link: "https://stardewvalleywiki.com/Ginger"}, {item: "Hazelnut", link: "https://stardewvalleywiki.com/Hazelnut"}, {item: "Holly", link: "https://stardewvalleywiki.com/Holly"}, {item: "Leek", link: "https://stardewvalleywiki.com/Leek"}, {item: "Magma Cap", link: "https://stardewvalleywiki.com/Magma_Cap"}, {item: "Morel", link: "https://stardewvalleywiki.com/Morel"}, {item: "Purple Mushroom", link: "https://stardewvalleywiki.com/Purple_Mushroom"}, {item: "Salmonberry", link: "https://stardewvalleywiki.com/Salmonberry"}, {item: "Snow Yam", link: "https://stardewvalleywiki.com/Snow_Yam"}, {item: "Spring Onion", link: "https://stardewvalleywiki.com/Spring_Onion"}, {item: "Wild Horseradish", link: "https://stardewvalleywiki.com/Wild_Horseradish"}, {item: "Winter Root", link: "https://stardewvalleywiki.com/Winter_Root"}],
        dislikes: "",
        events: []
    },
    {
        id: 10,
        name: "Maru",
        gender: "Female",
        pronouns: "She/Her",
        birthday: "Summer 10",
        location: [{address: "24 Mountain Road", link: "https://stardewvalleywiki.com/Carpenter%27s_Shop"}],
        bio: "Growing up with a carpenter and a scientist for parents, Maru acquired a passion for creating gadgets at a young age. When she isn't in her room, fiddling with tools and machinery, she sometimes does odd jobs at the local clinic. Friendly, outgoing, and ambitious, Maru would be quite a lucky match for a lowly newcomer such as yourself… Can you win her heart, or will she slip through your fingers and disappear from your life forever?",
        loves: [{item: "All Universal Loves", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Battery Pack", link: "https://stardewvalleywiki.com/Battery_Pack"}, {item: "Cauliflower", link: "https://stardewvalleywiki.com/Cauliflower"}, {item: "Cheese Cauliflower", link: "https://stardewvalleywiki.com/Cheese_Cauliflower"}, {item: "Diamond", link: "https://stardewvalleywiki.com/Diamond"}, {item: "Gold Bar", link: "https://stardewvalleywiki.com/Gold_Bar"}, {item: "Iridium Bar", link: "https://stardewvalleywiki.com/Iridium_Bar"}, {item: "Miner's Treat", link: "https://stardewvalleywiki.com/Miner%27s_Treat"}, {item: "Pepper Poppers", link: "https://stardewvalleywiki.com/Pepper_Poppers"}, {item: "Radioactive Bar", link: "https://stardewvalleywiki.com/Radioactive_Bar"}, {item: "Rhubarb Pie", link: "https://stardewvalleywiki.com/Rhubarb_Pie"}, {item: "Strawberry", link: "https://stardewvalleywiki.com/Strawberry"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "Copper Bar", link: "https://stardewvalleywiki.com/Copper_Bar"}, {item: "Iron Bar", link: "https://stardewvalleywiki.com/Iron_Bar"}, {item: "Oak Resin", link: "https://stardewvalleywiki.com/Oak_Resin"}, {item: "Pine Tar", link: "https://stardewvalleywiki.com/Pine_Tar"}, {item: "Quartz", link: "https://stardewvalleywiki.com/Quartz"}, {item: "Radioactive Ore", link: "https://stardewvalleywiki.com/Radioactive_Ore"}],
        dislikes: "",
        events: []
    },
    {
        id: 11,
        name: "Penny",
        gender: "Female",
        pronouns: "She/Her",
        birthday: "Fall 2",
        location: [{address: "The Trailer", link: "https://stardewvalleywiki.com/Trailer"}],
        bio: "Penny lives with her mom, Pam, in a little trailer by the river. While Pam is out carousing at the saloon, Penny quietly tends to her chores in the dim, stuffy room she is forced to call home. She is shy and modest, without any grand ambitions for life other than settling in and starting a family. She likes to cook (although her skills are questionable) and read books from the local library.",
        loves: [{item: "All Universal Loves (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Loves"}, {item: "Diamond", link: "https://stardewvalleywiki.com/Diamond"}, {item: "Emerald", link: "https://stardewvalleywiki.com/Emerald"}, {item: "Melon", link: "https://stardewvalleywiki.com/Melon"}, {item: "Poppy", link: "https://stardewvalleywiki.com/Poppy"}, {item: "Poppyseed Muffin", link: "https://stardewvalleywiki.com/Poppyseed_Muffin"}, {item: "Red Plate", link: "https://stardewvalleywiki.com/Red_Plate"}, {item: "Roots Platter", link: "https://stardewvalleywiki.com/Roots_Platter"}, {item: "Sandfish", link: "https://stardewvalleywiki.com/Sandfish"}, {item: "Tom Kha Soup", link: "https://stardewvalleywiki.com/Tom_Kha_Soup"}],
        likes: [{item: "All Universal Likes (see: exceptions)", link: "https://stardewvalleywiki.com/Friendship#Universal_Likes"}, {item: "All Milk", link: "https://stardewvalleywiki.com/Milk"}, {item: "All Artifacts", link: "https://stardewvalleywiki.com/Artifacts"}, {item: "Dandelion", link: "https://stardewvalleywiki.com/Dandelion"}, {item: "Leek", link: "https://stardewvalleywiki.com/Leek"}],
        dislikes: "",
        events: []
    }
];